/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/DOOR.glb -o src/models/Door.tsx --typescript -r public 
*/

import * as THREE from "three";
import { GLTF } from "three-stdlib";

type ActionName =
  | "polySurface13|Take 001|BaseLayer"
  | "polySurface11|Take 001|BaseLayer"
  | "polySurface16|Take 001|BaseLayer"
  | "polySurface9|Take 001|BaseLayer"
  | "polySurface18|Take 001|BaseLayer"
  | "polySurface17|Take 001|BaseLayer"
  | "polySurface31|Take 001|BaseLayer"
  | "polySurface35|Take 001|BaseLayer"
  | "polySurface36|Take 001|BaseLayer"
  | "DOOR_RIGHT|Take 001|BaseLayer"
  | "polySurface26|Take 001|BaseLayer"
  | "polySurface30|Take 001|BaseLayer"
  | "polySurface29|Take 001|BaseLayer"
  | "DOOR_LEFT|Take 001|BaseLayer";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

export type GLTFResult = GLTF & {
  nodes: {
    polySurface26: THREE.Mesh;
    polySurface30: THREE.Mesh;
    polySurface29: THREE.Mesh;
    polySurface31: THREE.Mesh;
    polySurface35: THREE.Mesh;
    polySurface36: THREE.Mesh;
    polySurface13: THREE.Mesh;
    polySurface11: THREE.Mesh;
    polySurface16: THREE.Mesh;
    polySurface9: THREE.Mesh;
    polySurface18: THREE.Mesh;
    polySurface17: THREE.Mesh;
  };
  materials: {
    aiStandardSurface2: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

/* useGLTF.preload("/models/DOOR.glb"); */
