/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/DOOR.glb -o src/models/Door.tsx --typescript -r public 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName =
  | "polySurface13|Take 001|BaseLayer"
  | "polySurface11|Take 001|BaseLayer"
  | "polySurface16|Take 001|BaseLayer"
  | "polySurface9|Take 001|BaseLayer"
  | "polySurface18|Take 001|BaseLayer"
  | "polySurface17|Take 001|BaseLayer"
  | "polySurface31|Take 001|BaseLayer"
  | "polySurface35|Take 001|BaseLayer"
  | "polySurface36|Take 001|BaseLayer"
  | "DOOR_RIGHT|Take 001|BaseLayer"
  | "polySurface26|Take 001|BaseLayer"
  | "polySurface30|Take 001|BaseLayer"
  | "polySurface29|Take 001|BaseLayer"
  | "DOOR_LEFT|Take 001|BaseLayer";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

export type GLTFResult = GLTF & {
  nodes: {
    polySurface26: THREE.Mesh;
    polySurface30: THREE.Mesh;
    polySurface29: THREE.Mesh;
    polySurface31: THREE.Mesh;
    polySurface35: THREE.Mesh;
    polySurface36: THREE.Mesh;
    polySurface13: THREE.Mesh;
    polySurface11: THREE.Mesh;
    polySurface16: THREE.Mesh;
    polySurface9: THREE.Mesh;
    polySurface18: THREE.Mesh;
    polySurface17: THREE.Mesh;
  };
  materials: {
    aiStandardSurface2: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/models/DOOR.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="DOOR" position={[543.27, 755.753, -7.917]}>
          <group
            name="DOOR_A"
            position={[-560.608, -692.213, 126.958]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={77.874}
          >
            <group name="DOOR_LEFT">
              <mesh
                name="polySurface26"
                geometry={nodes.polySurface26.geometry}
                material={materials.aiStandardSurface2}
                position={[-0.333, 0, 15.25]}
                rotation={[-Math.PI, 1.328, -Math.PI]}
              />
              <mesh
                name="polySurface30"
                geometry={nodes.polySurface30.geometry}
                material={materials.aiStandardSurface2}
                position={[-1.415, 0, 18.415]}
                rotation={[-Math.PI, 1.433, -Math.PI]}
              />
              <mesh
                name="polySurface29"
                geometry={nodes.polySurface29.geometry}
                material={materials.aiStandardSurface2}
                position={[-3.393, 0.667, 8.137]}
                rotation={[0, 1.47, 0]}
              />
            </group>
            <group name="DOOR_RIGHT">
              <mesh
                name="polySurface31"
                geometry={nodes.polySurface31.geometry}
                material={materials.aiStandardSurface2}
                position={[-2.824, 0, 22.544]}
                rotation={[0, 0.79, 0]}
              />
              <mesh
                name="polySurface35"
                geometry={nodes.polySurface35.geometry}
                material={materials.aiStandardSurface2}
                position={[1.862, 0, 17.22]}
                rotation={[-Math.PI, 1.442, -Math.PI]}
              />
              <mesh
                name="polySurface36"
                geometry={nodes.polySurface36.geometry}
                material={materials.aiStandardSurface2}
                position={[-3.761, 0, 10.436]}
                rotation={[0, 1.47, 0]}
              />
            </group>
            <mesh
              name="polySurface13"
              geometry={nodes.polySurface13.geometry}
              material={materials.aiStandardSurface2}
              position={[-2.189, -0.027, 4.37]}
              rotation={[-Math.PI, 1.474, -Math.PI]}
            />
            <mesh
              name="polySurface11"
              geometry={nodes.polySurface11.geometry}
              material={materials.aiStandardSurface2}
              position={[1.666, 1.634, 9.503]}
              rotation={[0, 1.302, 0]}
            />
            <mesh
              name="polySurface16"
              geometry={nodes.polySurface16.geometry}
              material={materials.aiStandardSurface2}
              position={[-1.835, 2.037, 22.596]}
              rotation={[0, 0.79, 0]}
            />
            <mesh
              name="polySurface9"
              geometry={nodes.polySurface9.geometry}
              material={materials.aiStandardSurface2}
              position={[-2.787, 0, 12.692]}
              rotation={[0, 0.79, 0]}
            />
            <mesh
              name="polySurface18"
              geometry={nodes.polySurface18.geometry}
              material={materials.aiStandardSurface2}
              position={[-3.614, 0, 24.632]}
              rotation={[0, 0.79, 0]}
            />
            <mesh
              name="polySurface17"
              geometry={nodes.polySurface17.geometry}
              material={materials.aiStandardSurface2}
              position={[-1.693, 0, 22.432]}
              rotation={[0, 0.79, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/DOOR.glb");
